/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package androidx.legacy.coreui;

public final class R {
    private R() {}

    public static final class attr {
        private attr() {}

        public static final int alpha = 0x7f040028;
        public static final int coordinatorLayoutStyle = 0x7f0400c6;
        public static final int font = 0x7f040123;
        public static final int fontProviderAuthority = 0x7f040125;
        public static final int fontProviderCerts = 0x7f040126;
        public static final int fontProviderFetchStrategy = 0x7f040127;
        public static final int fontProviderFetchTimeout = 0x7f040128;
        public static final int fontProviderPackage = 0x7f040129;
        public static final int fontProviderQuery = 0x7f04012a;
        public static final int fontStyle = 0x7f04012b;
        public static final int fontVariationSettings = 0x7f04012c;
        public static final int fontWeight = 0x7f04012d;
        public static final int keylines = 0x7f04016b;
        public static final int layout_anchor = 0x7f040171;
        public static final int layout_anchorGravity = 0x7f040172;
        public static final int layout_behavior = 0x7f040173;
        public static final int layout_dodgeInsetEdges = 0x7f04019f;
        public static final int layout_insetEdge = 0x7f0401a8;
        public static final int layout_keyline = 0x7f0401a9;
        public static final int statusBarBackground = 0x7f04023a;
        public static final int ttcIndex = 0x7f0402ae;
    }
    public static final class color {
        private color() {}

        public static final int notification_action_color_filter = 0x7f0600ad;
        public static final int notification_icon_bg_color = 0x7f0600ae;
        public static final int ripple_material_light = 0x7f0600b9;
        public static final int secondary_text_default_material_light = 0x7f0600bb;
    }
    public static final class dimen {
        private dimen() {}

        public static final int compat_button_inset_horizontal_material = 0x7f070053;
        public static final int compat_button_inset_vertical_material = 0x7f070054;
        public static final int compat_button_padding_horizontal_material = 0x7f070055;
        public static final int compat_button_padding_vertical_material = 0x7f070056;
        public static final int compat_control_corner_material = 0x7f070057;
        public static final int compat_notification_large_icon_max_height = 0x7f070058;
        public static final int compat_notification_large_icon_max_width = 0x7f070059;
        public static final int notification_action_icon_size = 0x7f070141;
        public static final int notification_action_text_size = 0x7f070142;
        public static final int notification_big_circle_margin = 0x7f070143;
        public static final int notification_content_margin_start = 0x7f070144;
        public static final int notification_large_icon_height = 0x7f070145;
        public static final int notification_large_icon_width = 0x7f070146;
        public static final int notification_main_column_padding_top = 0x7f070147;
        public static final int notification_media_narrow_margin = 0x7f070148;
        public static final int notification_right_icon_size = 0x7f070149;
        public static final int notification_right_side_padding_top = 0x7f07014a;
        public static final int notification_small_icon_background_padding = 0x7f07014b;
        public static final int notification_small_icon_size_as_large = 0x7f07014c;
        public static final int notification_subtext_size = 0x7f07014d;
        public static final int notification_top_pad = 0x7f07014e;
        public static final int notification_top_pad_large_text = 0x7f07014f;
    }
    public static final class drawable {
        private drawable() {}

        public static final int notification_action_background = 0x7f080086;
        public static final int notification_bg = 0x7f080087;
        public static final int notification_bg_low = 0x7f080088;
        public static final int notification_bg_low_normal = 0x7f080089;
        public static final int notification_bg_low_pressed = 0x7f08008a;
        public static final int notification_bg_normal = 0x7f08008b;
        public static final int notification_bg_normal_pressed = 0x7f08008c;
        public static final int notification_icon_background = 0x7f08008d;
        public static final int notification_template_icon_bg = 0x7f08008e;
        public static final int notification_template_icon_low_bg = 0x7f08008f;
        public static final int notification_tile_bg = 0x7f080090;
        public static final int notify_panel_notification_icon_bg = 0x7f080091;
    }
    public static final class id {
        private id() {}

        public static final int action_container = 0x7f090033;
        public static final int action_divider = 0x7f090035;
        public static final int action_image = 0x7f090036;
        public static final int action_text = 0x7f09003c;
        public static final int actions = 0x7f09003d;
        public static final int 