/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package androidx.loader;

public final class R {
    private R() {}

    public static final class attr {
        private attr() {}

        public static final int alpha = 0x7f040028;
        public static final int font = 0x7f040123;
        public static final int fontProviderAuthority = 0x7f040125;
        public static final int fontProviderCerts = 0x7f040126;
        public static final int fontProviderFetchStrategy = 0x7f040127;
        public static final int fontProviderFetchTimeout = 0x7f040128;
        public static final int fontProviderPackage = 0x7f040129;
        public static final int fontProviderQuery = 0x7f04012a;
        public static final int fontStyle = 0x7f04012b;
        public static final int fontVariationSettings = 0x7f04012c;
        public static final int fontWeight = 0x7f04012d;
        public static final int ttcIndex = 0x7f0402ae;
    }
    public static final class color {
        private color() {}

        public static final int notification_action_color_filter = 0x7f0600ad;
        public static final int notification_icon_bg_color = 0x7f0600ae;
        public static final int ripple_material_light = 0x7f0600b9;
        public static final int secondary_text_default_material_light = 0x7f0600bb;
    }
    public static final class dimen {
        private dimen() {}

        public static final int compat_button_inset_horizontal_material = 0x7f070053;
        public static final int compat_button_inset_vertical_material = 0x7f070054;
        public static final int compat_button_padding_horizontal_material = 0x7f070055;
        public static final int compat_button_padding_vertical_material = 0x7f070056;
        public static final int compat_control_corner_material = 0x7f070057;
        public static final int compat_notification_large_icon_max_height = 0x7f070058;
        public static final int compat_notification_large_icon_max_width = 0x7f070059;
        public static final int notification_action_icon_size = 0x7f070141;
        public static final int n